version: "3.3"

services:
  producer:
    build: producer
    command: python3 producer.py
    env_file:
      - local.env

  plotter:
    build: tickers_plotter
    command: gunicorn app:server --workers=2 -b 0.0.0.0:80
    env_file:
      - local.env
    ports:
      - "80:80"
    depends_on:
      - producer

  redis:
    image: redislabs/redistimeseries
